# Generated by Django 3.0.2 on 2020-01-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_auto_20200106_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='preco',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='preco_promocional',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
